import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import FormContainer from "../components/FormContainer";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Credit Risk Analysis</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero />
      <FormContainer />
      <Footer />
    </div>
  );
}
